name: Deploy

on: [push]

jobs:
#   copy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1

#     - name: Copy file via scp
#       uses: appleboy/scp-action@master
#       env:
#         HOST: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#       with:
#         source: "."
#         target: ${{ secrets.DEPLOYPATH }}
#         # ${{ secrets.DEPLOYPATH }}
#         # "/var/www/ihateregex.io/app"
  copy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - name: Copy file via scp
        uses: garygrossgarten/github-action-scp@release
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY }}
        with:
          local: "."
          remote: ${{ secrets.DEPLOYPATH }}
          # ${{ secrets.DEPLOYPATH }}
          # "/var/www/ihateregex.io/app"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.DEPLOYPATH }}
            yarn
            yarn build
            pm2 restart ihateregex
