name: Deploy Dev Branch

on: 
  push:
    branches:
    - develop

jobs:
  copy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Copy file via scp 2
        if: github.ref == 'refs/heads/develop'
        uses: garygrossgarten/github-action-scp@release       
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY }}
          local: "."
          remote: ${{ secrets.DEPLOYPATH }}
          recursive: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        if: github.ref == 'refs/heads/develop'
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.DEPLOYPATH }}
            yarn
            yarn build
            pm2 restart ihateregex
